### ISSUE TITLE
wrong documentation of tempo-synced LFO rate

### ISSUE THREAD

**Issue by othmar52** [mo-thunderz/lfo#2]
Hi,
[This line](https://github.com/mo-thunderz/lfo/blob/e7b8b7f5c0971ac02223ee9f7a02d4dbf2011ee7/lfo.h#L31) refers to ` see _freq_array` which does not exist.  

After some playing around i finally figured out how to get the desired tempo division in case sync mode is set to BPM locked.  
The unit for the argument of `setMode1Rate(float l_mode1_rate)` is **quarter notes**  

this means if you want a lfo cycle duration of `1 bar` you need to pass `1/4` or `0.25` as argument.  
```
argument | lfo cycle duration
---------------------------------
     .125|   2 bars
     .25 |   1 bar
     .5  |   half note
     1   |   quarter note
     2   |   1/8 note
     3   |   1/12 note
     4   |   1/16 note
     5   |   1/20 note
     6   |   1/24 note
     7   |   1/28 note
     8   |   1/32 note
     9   |   1/36 note
    10   |   1/40 note
    11   |   1/44 note
    12   |   1/48 note
    13   |   1/52 note
    14   |   1/56 note
    15   |   1/60 note
    16   |   1/64 note
```
consider to update the documentation

**Comment by mo-thunderz** [comment]
Thank you for addressing this. The doc was indeed outdated. I updated the code some time ago to make it more flexible. I have just updated the documentation and added your table :-)
